-- 코드를 입력하세요
SELECT P.PRODUCT_CODE,
       SUM(P.PRICE * DS.SALES_AMOUNT) PRICE
    FROM PRODUCT P
    LEFT JOIN OFFLINE_SALE DS ON P.PRODUCT_ID = DS.PRODUCT_ID 
    GROUP BY P.PRODUCT_CODE
    ORDER BY 2 DESC, 1