-- 코드를 입력하세요    
SELECT UGU.USER_ID,
       UGU.NICKNAME,
       CONCAT(UGU.CITY, ' ',UGU.STREET_ADDRESS1, ' ',UGU.STREET_ADDRESS2) '전체주소',
       CONCAT(SUBSTR(UGU.TLNO,1,3), '-',SUBSTR(UGU.TLNO,4,4), '-',SUBSTR(UGU.TLNO,8)) '전화번호'
    FROM USED_GOODS_BOARD UGB
    LEFT JOIN USED_GOODS_USER UGU ON UGB.WRITER_ID = UGU.USER_ID
    WHERE UGU.USER_ID IN (
        SELECT WRITER_ID FROM USED_GOODS_BOARD
        GROUP BY WRITER_ID
        HAVING COUNT(WRITER_ID) >=3
    )
    GROUP BY UGU.USER_ID
    ORDER BY UGU.USER_ID DESC
    