-- 코드를 입력하세요
WITH recursive TIME as (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM TIME where HOUR<23)

SELECT r.hour AS HOUR,
       COUNT(ANIMAL_ID) AS COUNT
    FROM ANIMAL_OUTS O
    RIGHT JOIN TIME R on HOUR(O.DATETIME) = R.HOUR
    GROUP BY 1
    ORDER BY 1