-- 코드를 입력하세요
SELECT UGU.USER_ID,
       UGU.NICKNAME,
       SUM(UGB.PRICE) TOTAL_SALES
    FROM USED_GOODS_BOARD UGB
    LEFT JOIN USED_GOODS_USER UGU ON UGB.WRITER_ID = UGU.USER_ID
    WHERE STATUS = 'DONE'
    GROUP BY UGB.WRITER_ID
    HAVING SUM(UGB.PRICE) >= 700000
    ORDER BY 3