-- 코드를 입력하세요
SELECT M.MEMBER_NAME,
       R.REVIEW_TEXT,
       DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW R 
LEFT JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID = (
    SELECT MEMBER_ID
        FROM (
            SELECT MEMBER_ID, COUNT(*)
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY 2 DESC
            LIMIT 1
        ) MAX_COUNTS_MEMBER
)
ORDER BY 3, 2


