-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', UGB.BOARD_ID, '/', UGF.FILE_ID, UGF.FILE_NAME, UGF.FILE_EXT) FILE_PATH
    FROM USED_GOODS_BOARD UGB
    LEFT OUTER JOIN USED_GOODS_FILE UGF ON UGB.BOARD_ID = UGF.BOARD_ID 
    WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)