-- 코드를 입력하세요
SELECT B.CATEGORY,
       SUM(BS.SALES) TOTAL_SALES
    FROM BOOK B
    LEFT JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
    WHERE DATE_FORMAT(BS.SALES_DATE, '%Y-%m-%d') >= '2022-01-01' 
        AND DATE_FORMAT(BS.SALES_DATE, '%Y-%m-%d') < '2022-02-01'
    GROUP BY 1
    ORDER BY 1