-- 코드를 입력하세요
SELECT B.BOOK_ID,
       AU.AUTHOR_NAME,
       DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
    FROM BOOK B
    LEFT JOIN AUTHOR AU ON B.AUTHOR_ID = AU.AUTHOR_ID
    WHERE B.CATEGORY = '경제'
    ORDER BY 3